sudo: required

services:
  - docker

before_install:
  - docker build -t kingsleyidoko/docker-react -f Dockerfile.dev .


script:
  - docker run  kingsleyidoko/docker-react:latest npm run test -- --coverage

language: generic