sudo: required

services:
  - docker

before_install:
  - docker build -t kingsleyidoko/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true kingsleyidoko/docker-react:latest npm run test -- --coverage

language: generic

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-317311251894"
#   bucket_path: "docker-react"
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY

deploy:
  provider: elasticbeanstalk
  on:
      branch: main
  access_key_id:
    secure: "AKIAUTYJZOW3KS6TRYEU"
  secret_access_key:
    secure: "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"
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-317311251894"